# Pandas Tutorial

In [37]:
# Importing pandas

import pandas as pd
import numpy as np

In [38]:
# Checking pandas version
pd.__version__

'1.1.3'

In [39]:
# Package description
pd?

Type:        module
String form: <module 'pandas' from '/home/luan/anaconda3/lib/python3.8/site-packages/pandas/__init__.py'>
File:        ~/anaconda3/lib/python3.8/site-packages/pandas/__init__.py
Docstring:  
pandas - a powerful data analysis and manipulation library for Python

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non-floating
    point data.
  - Size mutability: columns can be insert

# Introducing Pandas Objects

## Series

In [40]:
data = pd.Series([1,2,3,4,5])
data

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [41]:
# Obtaining Series values
print(data.values)

[1 2 3 4 5]


In [42]:
# Obtaining the index
data.index


RangeIndex(start=0, stop=5, step=1)

In [43]:
#Accessing data
print('Element {} from Series: {}\n'.format(0,data[0]))
# Using slices/Fatiando o array
print('Series Elements:\n')
print(data[0:4])

Element 0 from Series: 1

Series Elements:

0    1
1    2
2    3
3    4
dtype: int64


## Series as a generalization of numpy array

In [44]:
data = pd.Series([5,10,15,20,25],index = ['a','b','c','d','e'])
data

a     5
b    10
c    15
d    20
e    25
dtype: int64

In [45]:
# Accessing value by index
data['a']

5

In [46]:
# The indices can be non sequential
data.index = ['a',1,'b',2,'c']
print(data['a'],data[1],data['b'],data[2],data['c'])

5 10 15 20 25


### Series as specialized dictionary

In [47]:
population_dict = {'California': 38332521,
'Texas': 26448193,
'New York': 19651127,
'Florida': 19552860,
'Illinois': 12882135}
population = pd.Series(population_dict)

In [48]:
population['California']

38332521

In [49]:
#With Series is possible to perform array slicing in non-numeric data
population['California':'Florida']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

In [50]:
# By default, index is a integer sequence
pd.Series(range(2,7,2))

0    2
1    4
2    6
dtype: int64

In [51]:
# If data is a single value and multiple indices are given, the value is repeated to fill the indexes
pd.Series(10,index = range(3))

0    10
1    10
2    10
dtype: int64

In [52]:
# As seen before, data can be a dictionary, and its keys can be choosed by informing it in index argument
pd.Series({2:'a',1:'b',3:'c'},index = [3,2])


3    c
2    a
dtype: object

## The Pandas DataFrame Object

In [53]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
'Florida': 170312, 'Illinois': 149995}

In [54]:
area = pd.Series(area_dict)

In [55]:
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [56]:
states = pd.DataFrame({'population':population,'area':area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [57]:
#accessing the indices:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [58]:
#acessing the columns
states.columns

Index(['population', 'area'], dtype='object')

### DataFrame as specialized dictionary.

In [59]:
print('state área: \n')
states['area']

state área: 



California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

### Constructing DataFrame objects

In [60]:
# From a single series
pd.DataFrame(population,columns = ['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [61]:
# From a list of dicts

data = [{'a':i,'b':2*i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [62]:
# If some keys in the dictionary are missing, Pandas will fill them with NaN

pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [63]:
# From a dictionary of Series objects
pd.DataFrame({'population': population,
'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [64]:
# From a NumPy structured array
pd.DataFrame(np.random.rand(3,2),columns = ['foo','bar'],index = ['a','b','c'])

foo       bar
a  0.234605  0.221115
b  0.921501  0.693567
c  0.872576  0.326957

In [65]:
# From a NumPy structured array
A = np.zeros(3,dtype = [('A','i8'),('B','f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [66]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

## Pandas Index Object

In [67]:
# Index => immutable array or ordered set

In [68]:
ind = pd.Index([2,3,4,5,7,11])

### Index as immutable array

In [69]:
# its access is equal to ordinary lists
ind[1]

3

In [70]:
# Is also possible to perform array slicing
ind[::-1]

Int64Index([11, 7, 5, 4, 3, 2], dtype='int64')

In [71]:
# The main difference it is the fact that the Index object are immutable
ind[1]=0

TypeError: Index does not support mutable operations

### Index as ordered set/Index as ordered set

In [72]:
indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,3,5,7,11])
print('Intersection: ',indA & indB) #intersection
print('Union: ',indA | indB)
print('Symmetric Difference: ',indA^indB)

Intersection:  Int64Index([3, 5, 7], dtype='int64')
Union:  Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')
Symmetric Difference:  Int64Index([1, 2, 9, 11], dtype='int64')


In [73]:
#Using methods
print('Intersection:    ',indA.intersection(indB))
print('Union:   ',indA.union(indB))
print('Symmetric Difference:    ',indA.symmetric_difference(indB))

Intersection:     Int64Index([3, 5, 7], dtype='int64')
Union:    Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')
Symmetric Difference:     Int64Index([1, 2, 9, 11], dtype='int64')


# Data Indexing and Selection

In [74]:
data = pd.Series([0.25,0.5,0.75,1],index = ['a','b','c','d'])

In [75]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [76]:
# is possible to check indices using dictionary like expressions
print('a' in data)
print(data.keys())
print(list(data.items()))

True
Index(['a', 'b', 'c', 'd'], dtype='object')
[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]


## Series as one-dimensional array

In [77]:
# slicing is possible by explicit index(inclusive)
print(data['a':'c'])
# is also possible to slice by implicit integer index(exclusive)
print(data[0:2])
# masking
print(data[(data>0.3)&(data<0.6)])

a    0.25
b    0.50
c    0.75
dtype: float64
a    0.25
b    0.50
dtype: float64
b    0.5
dtype: float64


## indexers: loc, iloc e ix:


In [78]:
# To avoid confusion between implict and explicit indexing, pandas provides indexer attributes that exposes the indexing schemes
data = pd.Series(['a','b','c'],index = [1,3,5])
# explicit index when indexing
print('indexing:\n',data[1])
# implicit index when slicing
print('slicing:\n',data[1:3])

indexing:
 a
slicing:
 3    b
5    c
dtype: object


In [79]:
#.loc: explicit indexing
# iloc: implicit indexing
print(data.loc[1])
print(data.loc[1:5])

a
1    a
3    b
5    c
dtype: object


In [80]:
print(data.iloc[1])
print(data.iloc[1:5])

b
3    b
5    c
dtype: object


# Data Selection in DataFrame

## DataFrame as a dictionary

In [95]:
area = pd.Series({'California': 423967, 'Texas': 695662,
'New York': 141297, 'Florida': 170312,
'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
'New York': 19651127, 'Florida': 19552860,
'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [96]:
# Access like dictionary
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [97]:
# Access like class
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [98]:
# those methods are equivalent
data.area is data['area']

True

In [99]:
data.pop is data['pop']

False

In [102]:
# is possible to add another column by using a
# dictionary-like structure
data['density'] = data['pop']/data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

## DataFrame as two-dimensional array

In [105]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [106]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [107]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [111]:
data.iloc[:3,:2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [112]:
data.loc[:'Illinois',:'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [115]:
data.loc[data.density>100,['pop','density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [120]:
print(data)
data.iloc[0,2] = 90
print('\n')
print('After the indexing assignment: \n')
print(data)

              area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763


After the indexing assignment: 

              area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763


## Additional indexing conventions

In [129]:
print('slicing refers to rows: \n')
print(data['Florida':'Illinois'])
print('\n')
print(data[3:])
print('\n')
print(data[data.density>100])

slicing refers to rows: 

            area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763


            area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763


            area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121


# Operating on Data in Pandas